### ISSUE TITLE
V 1.0.6 errors

### ISSUE THREAD

**Issue by dmc1648** [alloy-project/alloy#13]
im getting a lot from different ip's
14:14:52.681530 INFO [76.98.113.213:56611 INC] Sync data returned unknown top block: 5524 -> 5575 [51 blocks (0 days) behind]

14:19:37.779990 WARNING [107.77.160.136:49857 INC] Exception in connectionHandler: TcpConnection::read, WSAGetOverlappedResult failed, result=10054, An existing connection was forcibly closed by the remote host.  

14:16:22.723155 WARNING [89.179.240.104:60189 INC] Exception in connectionHandler: TcpConnection::read, WSAGetOverlappedResult failed, result=10060, A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by retrosavedathome18** [comment]
I have this problem here:

2018-Jan-13 20:19:41.909496 INFO [daemon] alloy v1.0.6-alpha.7(0.1-g8edd99830)
2018-Jan-13 20:19:41.912504 INFO [daemon] Module folder: C:\Users\User\Downloads\Alloy-1.0.6-alpha-WIN64.zip\Release\alloyd.exe
2018-Jan-13 20:19:41.919522 INFO [daemon] Initializing p2p server...
2018-Jan-13 20:19:41.921527 INFO [node_server] Binding on 0.0.0.0:1810
2018-Jan-13 20:19:41.923530 INFO [node_server] Net service bound on 0.0.0.0:1810
2018-Jan-13 20:19:41.925537 INFO [node_server] Attempting to add IGD port mapping.
2018-Jan-13 20:19:43.070046 INFO [node_server] Added IGD port mapping.
2018-Jan-13 20:19:43.072053 INFO [daemon] P2p server initialized OK
2018-Jan-13 20:19:43.073056 INFO [daemon] Initializing core...
2018-Jan-13 20:19:43.083109 INFO [Blockchain] Loading blockchain...
2018-Jan-13 20:19:43.120937 INFO [BlockCacheSerializer] - loading block index...
2018-Jan-13 20:19:43.161734 INFO [BlockCacheSerializer] - loading transaction map...
2018-Jan-13 20:19:43.167255 INFO [BlockCacheSerializer] - loading spent keys...
2018-Jan-13 20:19:43.179288 INFO [BlockCacheSerializer] - loading outputs...
2018-Jan-13 20:19:43.209298 INFO [BlockCacheSerializer] - loading multi-signature outputs...
2018-Jan-13 20:19:43.212544 INFO [BlockCacheSerializer] Serialization time: 91ms
2018-Jan-13 20:19:43.213546 INFO [Blockchain] Loading blockchain indices for BlockchainExplorer...
2018-Jan-13 20:19:43.214549 INFO [BlockchainIndicesSerializer] - loading paymentID index...
2018-Jan-13 20:19:43.216554 INFO [BlockchainIndicesSerializer] - loading timestamp index...
2018-Jan-13 20:19:43.219564 INFO [BlockchainIndicesSerializer] - loading generated transactions index...
2018-Jan-13 20:19:43.228587 INFO [Blockchain] Blockchain initialized. last block: 5574, d0.h5.m22.s32 time ago, current difficulty: 90302106
2018-Jan-13 20:19:43.267997 INFO [daemon] Core initialized OK
2018-Jan-13 20:19:43.268999 INFO [daemon] Starting core rpc server on address 127.0.0.1:1811
2018-Jan-13 20:19:43.270003 INFO [daemon] Core rpc server started ok
2018-Jan-13 20:19:43.271006 INFO [daemon] Starting p2p net loop...
2018-Jan-13 20:19:43.273009 INFO [node_server] Starting node_server
2018-Jan-13 20:19:44.295913 INFO [protocol] 
2018-Jan-13 20:19:44.295913 INFO [protocol] **********************************************************************
2018-Jan-13 20:19:44.295913 INFO [protocol] You are now synchronized with the network. You may now start simplewallet.
2018-Jan-13 20:19:44.295913 INFO [protocol] 
2018-Jan-13 20:19:44.295913 INFO [protocol] Please note, that the blockchain will be saved only after you quit the daemon with "exit" command or if you use "save" command.
2018-Jan-13 20:19:44.295913 INFO [protocol] Otherwise, you will possibly need to synchronize the blockchain again.
2018-Jan-13 20:19:44.295913 INFO [protocol] 
2018-Jan-13 20:19:44.295913 INFO [protocol] Use "help" command to see the list of available commands.
2018-Jan-13 20:19:44.295913 INFO [protocol] **********************************************************************
2018-Jan-13 20:19:45.931094 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:19:45.936457 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:19:46.097636 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:19:46.102650 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:19:46.865548 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:19:46.870933 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:19:48.893525 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:19:48.898967 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:19:49.268977 INFO [txpool] transaction fee is not enough: 0.000000100000, minimum fee: 0.000001000000
2018-Jan-13 20:19:49.271806 INFO [core] Transaction verification failed: <8c9d4426cf34977b15dd078c8999059af3439c5bed0b190a0f70846942f278c8>
2018-Jan-13 20:19:49.275726 INFO [protocol] [195.91.234.78:53377 INC] Tx verification failed
2018-Jan-13 20:19:50.068444 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:19:50.074372 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:19:55.030419 INFO [daemon] alloy v1.0.6-alpha.7(0.1-g8edd99830)
2018-Jan-13 20:19:55.033414 INFO [daemon] Module folder: C:\Users\User\Downloads\Alloy-1.0.6-alpha-WIN64.zip\Release\alloyd.exe
2018-Jan-13 20:19:55.037425 INFO [daemon] Initializing p2p server...
2018-Jan-13 20:19:55.039430 INFO [node_server] Binding on 0.0.0.0:1810
2018-Jan-13 20:19:55.040432 INFO [node_server] Net service bound on 0.0.0.0:1810
2018-Jan-13 20:19:55.042437 INFO [node_server] Attempting to add IGD port mapping.
2018-Jan-13 20:19:56.184242 INFO [node_server] Added IGD port mapping.
2018-Jan-13 20:19:56.186252 INFO [daemon] P2p server initialized OK
2018-Jan-13 20:19:56.187255 INFO [daemon] Initializing core...
2018-Jan-13 20:19:56.197813 INFO [Blockchain] Loading blockchain...
2018-Jan-13 20:19:56.199014 INFO [BlockCacheSerializer] - loading block index...
2018-Jan-13 20:19:56.200987 INFO [BlockCacheSerializer] - loading transaction map...
2018-Jan-13 20:19:56.205999 INFO [BlockCacheSerializer] - loading spent keys...
2018-Jan-13 20:19:56.218387 INFO [BlockCacheSerializer] - loading outputs...
2018-Jan-13 20:19:56.241450 INFO [BlockCacheSerializer] - loading multi-signature outputs...
2018-Jan-13 20:19:56.242611 INFO [BlockCacheSerializer] Serialization time: 43ms
2018-Jan-13 20:19:56.243615 INFO [Blockchain] Loading blockchain indices for BlockchainExplorer...
2018-Jan-13 20:19:56.245621 INFO [BlockchainIndicesSerializer] - loading paymentID index...
2018-Jan-13 20:19:56.246623 INFO [BlockchainIndicesSerializer] - loading timestamp index...
2018-Jan-13 20:19:56.249632 INFO [BlockchainIndicesSerializer] - loading generated transactions index...
2018-Jan-13 20:19:56.259042 INFO [Blockchain] Blockchain initialized. last block: 5574, d0.h5.m22.s45 time ago, current difficulty: 90302106
2018-Jan-13 20:19:56.297372 INFO [daemon] Core initialized OK
2018-Jan-13 20:19:56.298374 INFO [daemon] Starting core rpc server on address 127.0.0.1:1811
2018-Jan-13 20:19:56.299377 INFO [daemon] Core rpc server started ok
2018-Jan-13 20:19:56.301383 INFO [daemon] Starting p2p net loop...
2018-Jan-13 20:19:56.301383 INFO [node_server] Starting node_server
2018-Jan-13 20:19:58.280763 INFO [protocol] 
2018-Jan-13 20:19:58.280763 INFO [protocol] **********************************************************************
2018-Jan-13 20:19:58.280763 INFO [protocol] You are now synchronized with the network. You may now start simplewallet.
2018-Jan-13 20:19:58.280763 INFO [protocol] 
2018-Jan-13 20:19:58.280763 INFO [protocol] Please note, that the blockchain will be saved only after you quit the daemon with "exit" command or if you use "save" command.
2018-Jan-13 20:19:58.280763 INFO [protocol] Otherwise, you will possibly need to synchronize the blockchain again.
2018-Jan-13 20:19:58.280763 INFO [protocol] 
2018-Jan-13 20:19:58.280763 INFO [protocol] Use "help" command to see the list of available commands.
2018-Jan-13 20:19:58.280763 INFO [protocol] **********************************************************************
2018-Jan-13 20:19:58.306491 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:19:58.314487 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:19:58.762558 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:19:58.767575 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:19:59.310527 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:19:59.315904 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:20:00.218717 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:20:00.223740 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:20:00.800968 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:20:00.806125 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:20:09.507967 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:20:09.513484 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:20:10.421356 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:20:10.426402 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:20:10.945820 INFO [core] 
2018-Jan-13 20:20:10.945820 INFO [core] **********************************************************************
2018-Jan-13 20:20:10.945820 INFO [core] The daemon will start synchronizing with the network. It may take up to several hours.
2018-Jan-13 20:20:10.945820 INFO [core] 
2018-Jan-13 20:20:10.945820 INFO [core] You can set the level of process detailization* through "set_log <level>" command*, where <level> is between 0 (no details) and 4 (very verbose).
2018-Jan-13 20:20:10.945820 INFO [core] 
2018-Jan-13 20:20:10.945820 INFO [core] Use "help" command to see the list of available commands.
2018-Jan-13 20:20:10.945820 INFO [core] 
2018-Jan-13 20:20:10.945820 INFO [core] Note: in case you need to interrupt the process, use "exit" command. Otherwise, the current progress won't be saved.
2018-Jan-13 20:20:10.945820 INFO [core] **********************************************************************
2018-Jan-13 20:20:13.220121 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:20:13.225134 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:20:18.240549 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:20:18.246566 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:20:21.349500 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:20:21.355515 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:20:24.814240 INFO [txpool] tx used wrong inputs, rejected
2018-Jan-13 20:20:24.816176 ERROR [core] Transaction verification failed: <f6b3977ae0b63c415d6ff761adf4ab13511d1cffb2327ded9c5972526f0d7721>
2018-Jan-13 20:20:24.819185 INFO [protocol] [145.129.59.165:59756 INC] Tx verification failed
2018-Jan-13 20:20:24.824204 INFO [txpool] tx used wrong inputs, rejected
2018-Jan-13 20:20:24.827555 ERROR [core] Transaction verification failed: <b93eea53ba2c14d82b18b143a027cfdc491d1225f7a5662cd92b8a4c6d69089e>
2018-Jan-13 20:20:24.830562 INFO [protocol] [145.129.59.165:59756 INC] Tx verification failed
2018-Jan-13 20:20:29.285264 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:20:29.291312 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:20:41.464638 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:20:41.469651 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:20:41.521788 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:20:41.526713 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:20:46.518962 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:20:46.523973 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:20:51.529958 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:20:51.533968 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:20:56.542710 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:20:56.549725 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:21:01.558435 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:21:01.564063 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:21:03.823270 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:21:03.829724 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:21:04.151052 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:21:04.162084 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:21:04.187458 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:21:04.198447 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:21:04.450219 INFO [txpool] transaction fee is not enough: 0.000000100000, minimum fee: 0.000001000000
2018-Jan-13 20:21:04.454238 INFO [core] Transaction verification failed: <8c9d4426cf34977b15dd078c8999059af3439c5bed0b190a0f70846942f278c8>
2018-Jan-13 20:21:04.466272 INFO [protocol] [78.10.91.49:59203 INC] Tx verification failed
2018-Jan-13 20:21:06.568938 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:21:06.581974 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:21:11.596249 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:21:11.616337 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:21:13.474807 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:21:13.479963 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
2018-Jan-13 20:21:16.632280 INFO [Blockchain] Failed to check ring signature for tx <7e87da9e2051d0a2ffb02b4a66413ad32e334ff38c9314b61be7776ce6e701b7>
2018-Jan-13 20:21:16.637232 INFO [Blockchain] Failed to check ring signature for tx <dbc1845963a5e36b320fd4b248941968805ac3494b42300fde9dbb4dd5d3ef02>
